### ISSUE TITLE
Is this pipeline still available?

### ISSUE THREAD

**Issue by Abe410** [matteobrv/cryptoNER#1]
Hi

Is this pipeline still available?

I tried cloning it using ```!python -m spacy project clone pipelines/CryptoNER``` but I got the following error:

```
Can't clone pipelines/CryptoNER. Make sure the directory exists in the repo (branch 'v3')
https://github.com/explosion/projects
```

**Comment by matteobrv** [comment]
Hi @Abe410 thank you for your interest in this project. Unfortunately, the code-base in this repo is a bit dated and I'm not very familiar with the latest spaCy updates. I might come back to this project sometime in the future, but I don't have time to actively maintain it at the moment.
